### PR TITLE
Calcuate string/char array size correctly

### PR DESCRIPTION
**Pull request by jonathanchristison**
Fix for issues brought up in https://github.com/Diaoul/arduino-ESP8266/pull/11

### CODE REVIEW

**Comment by jonathanchristison** [comment]
You're right its pointless, I thought it might be necessary to also send the null terminator but after a few quick tests it seems fine without.

**Comment by lasselukkari** [comment]
I only ran one test with a char *  but it seems that the problem is fixed now. Good work!

**Comment by lasselukkari** [comment]
I ran some more tests. Everything is working again as it should. Thanks again!

**Comment by Diaoul** [comment]
Thanks for the fix :+1:

**Pull request merged**
